version: '3.8'

services:
  backend:
    container_name: backend
    environment:
      ACTIVE_PROFILE: 'local'
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: alexandria
      POSTGRES_USER: alexandria_login
      POSTGRES_PASSWORD: rotpasdbalexandria
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: thekillermaps@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Robokop412
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmindata:
